### PR TITLE
Add a REQUIRE_SSL variable, so we can disable SSLify

### PR DESCRIPTION
**Pull request by osteele**
This is intended to help with #143 abe.build.olin certificates are broken.

### CODE REVIEW

**Comment by newsch** [comment]
I added `REQUIRE_SSL` to Heroku's `app.json`, so it will populate automatically.

**Comment by osteele** [comment]
No hurry, since there’s a workaround. Let’s take time to get this right. Maybe that means not using this PR, and doing it in gunicorn instead.

**Comment by osteele** [comment]
A question is whether automatic cert renewal happens at a known route, that we can whitelist from HTTPS upgrade in order not to have to manually disable SSL when the renewal takes place.  If so, this might be a reason to keep HTTPS upgrade in Flask (where I know SSLIfy has per-route control) instead of moving it to gunicorn (where I don’t know if this is possible). In that case we wouldn’t need an environment setting for it, though.

**Comment by osteele** [comment]
ACM uses a fixed prefix `/.well-known/acme-challenge/`. I’m closing this PR, and I’ll create another that permanently whitelists that prefix, instead of using an env to disable HSTS for all routes.

https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.8.3

**Comment by osteele** [comment]
Replaced by PR #148.

**Pull request closed without merging**
